services:
  db-master:
    build:
      context: ./context/mysql
    environment:
      MYSQL_DATABASE: 'l18_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
    - '3308:3308'
    expose:
    - '3308'
    volumes:
    - ./data/master:/var/lib/mysql
    - ./config/master:/etc/mysql/conf.d
    - ./entrypoint/master/:/docker-entrypoint-initdb.d/
    networks:
      - p18

  db-slave-1:
    build:
      context: ./context/mysql
    environment:
      MYSQL_DATABASE: 'l18_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3320:3308'
    expose:
      - '3320'
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./config/slave1:/etc/mysql/conf.d
    networks:
      - p18

  db-slave-2:
    build:
      context: ./context/mysql
    environment:
      MYSQL_DATABASE: 'l18_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3330:3308'
    expose:
      - '3330'
    volumes:
      - ./data/slave2:/var/lib/mysql
      - ./config/slave2:/etc/mysql/conf.d
    networks:
      - p18

  php:
    build:
      context: ./context/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - p18

networks:
  p18:
    driver: bridge